[package]
name = "fiber-sphinx"
version = "2.3.0"
edition = "2021"
license-file = "COPYING.md"
description = "A Rust implementation of the Sphinx mix network."
documentation = "https://docs.rs/fiber-sphinx"
homepage = "https://github.com/nervosnetwork/fiber-sphinx"

[dependencies]
secp256k1 = { version = "0.30", features = ["serde"] }
sha2 = "0.10.8"
hmac = "0.12.1"
thiserror = "1.0"
chacha20 = "0.9.1"
subtle = "2.6"
zeroize = { version = "1.8", features = ["derive"] }

[dev-dependencies]
hex-conservative = "0.2.1"
